name: setup-site

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Install Auth0 CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/auth0/auth0-cli/main/install.sh | sh
          echo "$HOME/.auth0/bin" >> $GITHUB_PATH

      - name: Set up authentication
        run: |
          export PATH="$HOME/.auth0/bin:$PATH"
          chmod +x .github/workflows/setup-auth.sh
          .github/workflows/setup-auth.sh
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          SITE_ADMIN: ${{ secrets.SITE_ADMIN }}
          REPO_NAME: ${{ github.repository }}
