name: setup-site

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting setup"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Auth0 CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/auth0/auth0-cli/main/install.sh | sh
          export PATH="$HOME/.auth0/bin:$PATH"

      - name: Set up authentication
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          SITE_ADMIN: ${{ secrets.SITE_ADMIN }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          chmod +x .github/workflows/setup-auth.sh
          export PATH="$HOME/.auth0/bin:$PATH"
          .github/workflows/setup-auth.sh
